name: echo.yaml

on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  git-release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: echo
        run: |
          echo ${{ github.event.push }}
          echo ${{ github.event.push.commits }}
          for var in "${{ github.event.push.commits }}"
            do
              echo var = $var.message
            done
