name: Event Git Release

on:
  push:
    branches:
      - main

jobs:
  git-release:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.release-tag.outputs.tag }}
      major_tag: ${{ steps.release-tag.outputs.major_tag }}
      release_tag: ${{ steps.release-tag.outputs.release_tag }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Check PR Merge
        id: check-merge
        run: |
          echo "PR from dev to main has been merged."
          echo "${{ github.event.head_commit.message }}"

      - name: Parse version from Merged-PR
        id: parse-tag
        run: |
          echo "tag=$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}[a-z]{0,2}')" >> $GITHUB_OUTPUT \
            && echo "major_tag=$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,3}')" >> $GITHUB_OUTPUT

      - name: Validate tag
        id: validate-tag
          if [ -z ${{ steps.parse-tag.outputs.tag }} ]; then
            echo "tag=$(echo '${{ github.sha }}')" >> $GITHUB_OUTPUT
          else
            echo "tag=$(echo '${{ steps.parse-tag.outputs.tag }}')" >> $GITHUB_OUTPUT
          fi

          if [ -z ${{ steps.parse-tag.outputs.major_tag }} ]; then
            echo "major_tag=$(echo '${{ github.sha }}')" >> $GITHUB_OUTPUT
          else
            echo "tag=$(echo '${{ steps.parse-tag.outputs.major_tag }}')" >> $GITHUB_OUTPUT
          fi

      - name: Get Commits
        id: get-commits
        run: |
          echo "## ${{ steps.validate-tag.outputs.tag }} Changes"  > ./git.log.txt
          git log --oneline ${{ github.event.before }}...${{ github.event.after }} >> ./git.log.txt

      - name: Set release tag
        id: release-tag
        run: |
          echo "release_tag=$(echo ${{ steps.validate-tag.outputs.tag }} | cut -c1-20)" >> $GITHUB_OUTPUT
          echo "tag is ${{ steps.validate-tag.outputs.tag }}"
          echo "major_tag is ${{ steps.validate-tag.outputs.major_tag }}"
          
      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.validate-tag.outputs.release_tag }}
          release_name: ${{ steps.validate-tag.outputs.release_tag }}
          body_path: ./git.log.txt
          draft: false
          prerelease: false

      - name: Create Draft Release
        if: ${{ failure() && steps.release.outcome == 'failure' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: draft_tag
          release_name: draft Release
          body: |
            ## Changes
          draft: true
          prerelease: false
