name: Read Commit Description

on:
  push:
    branches:
      - main

jobs:
  read-commit-description:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read commit message description from github push event
        run: |
          # Get the latest commit hash
          COMMIT=${{ github.event.push.message }}
          COMMITS=${{ github.event.push.commits}}

          echo ${{ github.event.head_commit.message }}
          echo ${{ github.event.before }}
          echo ${{ github.event.after }}
          echo ${{ github.event.base_ref }}

      - name: Read commit message description
        run: |
          # Get the latest commit hash
          COMMIT_HASH=$(git rev-parse HEAD)

          # Extract the description (body) from the commit message
          COMMIT_DESCRIPTION=$(git log -1 --pretty=format:%B $COMMIT_HASH | tail -n +2)

          echo "Commit Description: $COMMIT_DESCRIPTION"
